version: '3.8'

services:
  app:
    image: creatly-dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./bin/:/root/


  mongodb:
    image: mongo:latest
    container_name: mongodb-creatly-dev-compose
    environment:
      MONGO_INITDB_DATABASE: creatly_task
    ports:
      - 27018:27017